import { existsSync } from "node:fs";
import { join, relative } from "node:path";
import type { AppletPackage } from "./load.ts";
import { REPO_ROOT } from "./load.ts";

/**
 * The applet catalog, generated from the packages that are actually installed.
 *
 * Per-applet prose used to be appended to the README, which made "add an
 * applet" a diff against a shared file — two applets, one conflict, over
 * paragraphs that have nothing to do with each other. So docs moved into the
 * package (`applets/<id>/README.md`) and this renders the index over them.
 * Nothing to append to; `kona docs` is always current, plugins included.
 */

const cell = (s: string) => s.replace(/\|/g, "\\|");

/** One line per applet: what it is, what it needs, where its docs live. */
export function catalogMarkdown(packages: AppletPackage[]): string {
  const rows = packages.map((p) => {
    const { def } = p;
    const readme = join(p.dir, "README.md");
    const where = existsSync(readme)
      ? p.source === "repo"
        ? `[docs](${relative(REPO_ROOT, readme)})`
        : "`README.md`"
      : "—";
    const labels = (def.labels ?? []).map((l) => `\`${l}\``).join(" ");
    return `| \`${def.id}\` | ${cell(def.title)} | ${cell(def.summary ?? "")} | ${labels} | ${where} |`;
  });
  const needs = packages
    .filter((p) => p.def.requires?.length)
    .map((p) => `- \`${p.def.id}\` — ${p.def.requires!.join("; ")}`);

  return [
    `# Applets (${packages.length})`,
    "",
    "Generated by `kona docs` from the applets this machine has loaded.",
    "",
    "| id | title | what it is | labels | docs |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
    ...(needs.length ? ["", "## What they need", "", ...needs] : []),
    "",
  ].join("\n");
}

/** The plain-text listing `kona ls` prints. */
export function catalogLines(packages: AppletPackage[]): string[] {
  const width = Math.max(...packages.map((p) => p.def.id.length), 0);
  return packages.map((p) => {
    const tag = p.source === "plugin" ? "  (plugin)" : "";
    return `${p.def.id.padEnd(width)}  ${p.def.summary ?? ""}${tag}`;
  });
}
